export const navigation = [
  {
    title: 'Introduction',
    links: [
      { title: 'Getting started', href: '/' },
      { title: 'Installation', href: '/docs/installation' },
    ],
  },
  {
    title: 'Configuration',
    links: [
      { title: 'Configuration', href: '/docs/configuration' },
      { title: 'Keys', href: '/docs/keys' },
      { title: 'Themes & Layouts', href: '/docs/themes-and-layouts' },
      { title: 'Plugins', href: '/docs/plugins' },
      { title: 'Events', href: '/docs/events' },
      { title: 'CLI', href: '/docs/cli' },
      { title: 'Service', href: '/docs/service' },
    ],
  },
  {
    title: 'Builtin Modules',
    links: [
      { title: 'Applications', href: '/docs/builtins/applications' },
      { title: 'Runner', href: '/docs/builtins/runner' },
      { title: 'Finder', href: '/docs/builtins/finder' },
      { title: 'Bookmarks', href: '/docs/builtins/bookmarks' },
      { title: 'Websearch', href: '/docs/builtins/websearch' },
      { title: 'Symbols', href: '/docs/builtins/symbols' },
      { title: 'Emojis', href: '/docs/builtins/emojis' },
      { title: 'Clipboard', href: '/docs/builtins/clipboard' },
      { title: 'Windows', href: '/docs/builtins/windows' },
      { title: 'SSH', href: '/docs/builtins/ssh' },
      { title: 'Hyprland Keybinds', href: '/docs/builtins/hyprland-keybinds' },
      { title: 'Custom Commands', href: '/docs/builtins/custom-commands' },
      { title: 'Switcher', href: '/docs/builtins/switcher' },
      { title: 'Calculator', href: '/docs/builtins/calc' },
      { title: 'Commands', href: '/docs/builtins/commands' },
      { title: 'Translation', href: '/docs/builtins/translation' },
      { title: 'XDPH Picker', href: '/docs/builtins/xdphpicker' },
      { title: 'Dmenu', href: '/docs/builtins/dmenu' },
      { title: 'AI', href: '/docs/builtins/ai' },
    ],
  },
]
